server:
  port: 9000
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/plain
      - image/gif
spring:
  datasource:
    url: jdbc:postgresql:globe42
    username: globe42
    password: globe42
    hikari:
      maximum-pool-size: 4
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jpa:
    open-in-view: false
management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      expose: '*'

---
spring:
  profiles: demo
  flyway:
    locations: classpath:/db/migration,classpath:/demo/db/migration
