server:
  port: 9000
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/plain
      - image/gif
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql:globe42
    username: globe42
    password: globe42
    hikari:
      maximum-pool-size: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

---
spring:
  profiles: demo
  flyway:
    locations: classpath:/db/migration,classpath:/demo/db/migration
